// Date: 8/9/2013 12:06:07 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package agkz.mods.lazerz.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelConjurationTable extends ModelBase
{
  //fields
    ModelRenderer BottomBox;
    ModelRenderer UpperBox;
    ModelRenderer platformTop;
    ModelRenderer BaseFoot1;
    ModelRenderer BaseFoot2;
    ModelRenderer BaseFoot3;
    ModelRenderer BaseFoot4;
    ModelRenderer BaseLeg1;
    ModelRenderer BaseLeg2;
    ModelRenderer BaseLeg3;
    ModelRenderer BaseLeg4;
    ModelRenderer FrontPeice;
  
  public ModelConjurationTable()
  {
    textureWidth = 128;
    textureHeight = 32;
    
      BottomBox = new ModelRenderer(this, 56, 15);
      BottomBox.addBox(0F, 0F, 0F, 12, 77, 12);
      BottomBox.setRotationPoint(-6F, 17F, -6F);
      BottomBox.setTextureSize(128, 32);
      BottomBox.mirror = true;
      setRotation(BottomBox, 0F, 0F, 0F);
      UpperBox = new ModelRenderer(this, 25, 0);
      UpperBox.addBox(-0.5F, 0F, -0.5F, 11, 6, 11);
      UpperBox.setRotationPoint(-5F, 9F, -5F);
      UpperBox.setTextureSize(128, 32);
      UpperBox.mirror = true;
      setRotation(UpperBox, 0F, 0F, 0F);
      
      platformTop = new ModelRenderer(this, 0, 17);
      platformTop.addBox(0F, 0F, 0F, 14, 1, 14);
      platformTop.setRotationPoint(-7F, 8F, -7F);
      platformTop.setTextureSize(128, 32);
      platformTop.mirror = true;
      setRotation(platformTop, 0F, 0F, 0F);
      
      BaseFoot1 = new ModelRenderer(this, 8, 5);
      BaseFoot1.addBox(0F, 0F, 0F, 4, 1, 4);
      BaseFoot1.setRotationPoint(4F, 23F, 4F);
      BaseFoot1.setTextureSize(128, 32);
      BaseFoot1.mirror = true;
      setRotation(BaseFoot1, 0F, 0F, 0F);
      
      BaseFoot2 = new ModelRenderer(this, 8, 5);
      BaseFoot2.addBox(0F, 0F, 0F, 4, 1, 4);
      BaseFoot2.setRotationPoint(-8F, 23F, -8F);
      BaseFoot2.setTextureSize(128, 32);
      BaseFoot2.mirror = true;
      setRotation(BaseFoot2, 0F, 0F, 0F);
      
      BaseFoot3 = new ModelRenderer(this, 8, 5);
      BaseFoot3.addBox(0F, 0F, 0F, 4, 1, 4);
      BaseFoot3.setRotationPoint(-8F, 23F, 4F);
      BaseFoot3.setTextureSize(128, 32);
      BaseFoot3.mirror = true;
      setRotation(BaseFoot3, 0F, 0F, 0F);
      
      BaseFoot4 = new ModelRenderer(this, 8, 5);
      BaseFoot4.addBox(0F, 0F, 0F, 4, 1, 4);
      BaseFoot4.setRotationPoint(4F, 23F, -8F);
      BaseFoot4.setTextureSize(128, 32);
      BaseFoot4.mirror = true;
      setRotation(BaseFoot4, 0F, 0F, 0F);
      
      BaseLeg1 = new ModelRenderer(this, 0, 0);
      BaseLeg1.addBox(0.5F, 0F, 0.5F, 2, 10, 2);
      BaseLeg1.setRotationPoint(4F, 16F, 4F);
      BaseLeg1.setTextureSize(128, 32);
      BaseLeg1.mirror = true;
      setRotation(BaseLeg1, 0.0698132F, 0F, -0.0698132F);
      
      BaseLeg2 = new ModelRenderer(this, 0, 0);
      BaseLeg2.addBox(0.5F, 0F, 0.5F, 2, 10, 2);
      BaseLeg2.setRotationPoint(-7F, 16F, 4F);
      BaseLeg2.setTextureSize(128, 32);
      BaseLeg2.mirror = true;
      setRotation(BaseLeg2, 0.0698132F, 0F, 0.0698132F);
      
      BaseLeg3 = new ModelRenderer(this, 0, 0);
      BaseLeg3.addBox(0.5F, 0F, 0.5F, 2, 10, 2);
      BaseLeg3.setRotationPoint(4F, 16F, -7F);
      BaseLeg3.setTextureSize(128, 32);
      BaseLeg3.mirror = true;
      setRotation(BaseLeg3, -0.0698132F, 0F, -0.0698132F);
      
      BaseLeg4 = new ModelRenderer(this, 0, 0);
      BaseLeg4.addBox(0.5F, 0F, 0.5F, 2, 10, 2);
      BaseLeg4.setRotationPoint(-7F, 16F, -7F);
      BaseLeg4.setTextureSize(128, 32);
      BaseLeg4.mirror = true;
      setRotation(BaseLeg4, -0.0698132F, 0F, 0.0698132F);
      
      FrontPeice = new ModelRenderer(this, 8, 0);
      FrontPeice.addBox(0.5F, 0.687F, 0.871F, 3, 3, 1);
      FrontPeice.setRotationPoint(0F, 13F, -7F);
      FrontPeice.setTextureSize(128, 32);
      FrontPeice.mirror = true;
      setRotation(FrontPeice, 0F, 0F, 0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    BottomBox.render(f5);
    UpperBox.render(f5);
    platformTop.render(f5);
    BaseFoot1.render(f5);
    BaseFoot2.render(f5);
    BaseFoot3.render(f5);
    BaseFoot4.render(f5);
    BaseLeg1.render(f5);
    BaseLeg2.render(f5);
    BaseLeg3.render(f5);
    BaseLeg4.render(f5);
    FrontPeice.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
